name = "SMLMClustering"
uuid = "5e733723-370a-41a4-ac41-ff3a91b0b806"
authors = ["klidke@unm.edu"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
